modLoader = "javafml"
loaderVersion = "[${forge},)"
issueTrackerURL = "https://github.com/rhysdh540/createlimited/issues"
license = "GPL-3.0"

[[mods]]
modId = "ntl"
version = "${version}"
displayName = "Create: No Train Limits"
authors = "rdh"
description = '''
y'all train nerds are weird
'''
logoFile = "icon.png"

[[dependencies.ntl]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ntl]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ntl]]
modId="create"
mandatory=true
versionRange="[${create_forge},)"
ordering="NONE"
side="BOTH"