modLoader = "javafml"
loaderVersion = "[${forge},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId="create"
mandatory=true
versionRange="${create_forge}"
ordering="NONE"
side="BOTH"